### ISSUE TITLE
Allow users more control over how a cluster scales

### ISSUE THREAD

**Issue by calebwin** [banyan-team/banyan-julia#15]
Let users specify a minimum number of workers for a cluster (default is 0 compute workers) and the time of inactivity before which a cluster starts to scale down (default is 10 minutes). Users should be able to specify this either through the API or from the dashboard. This is the cooldown time.

We should also let users "warm up" a cluster given a number of workers to warm up the cluster with. This will simply run an empty job with some number of workers. Warmups should also be schedule-able so that a warmup can be scheduled to occur every morning for example.

**Comment by cailinw** [comment]
- [x] Allow specifying min number of workers through API
- [ ] Allow specifying min number of workers from dashboard
- [x] Allow specifying scale-down time for nodes through API
- [x] Allow specifying scale-down time for nodes from dashboard
- [x] Implement `warmup_cluster(nworkers)`
- [x] Implement scheduling warmup

**Comment by cailinw** [comment]
#54

**Comment by calebwin** [comment]
Done!

We should do the UI for this soon though.
