### ISSUE TITLE
Faster time to first job

### ISSUE THREAD

**Issue by calebwin** [banyan-team/banyan-julia#51]
There should be a `wait_for_cluster` function that polls till the cluster is running and a `wait_for_workers` function that runs an empty Slurm job with `sbatch` with the given number of workers.

Then, we should modify `create_cluster` to call `wait_for_cluster` and `create_job` to also call `wait_for_cluster`.

Finally, `create_cluster` should have an option to start with an initial number of workers. The # of workers should be converted into a # of nodes and used to initialize the cluster with that as a minimum number of nodes. Then, when the first job is run, the # of nodes is updated to be 0. This allows the cluster head node and job nodes to be created _at the same time_ instead of one having to happen before the next. It means that the user has a much simpler onboarding expience: just call `create_cluster` with `num_initial_workers` specified, wait for it to return, and then run `create_job` and it should start the job in not more than a couple minutes. Total time to start a job should be not more than 15-20 minutes which is almost as good as the 5-10 minutes that Coiled has.

**Comment by calebwin** [comment]
Relevant issue: https://github.com/aws/aws-parallelcluster/issues/3322

Also, in addition to `wait_for_workers`, there should also be a `wait_for_job` that will poll until a job is available. This will involve a backend f sending a message to the cluster which sends something to the client side indicating the availability of the job.

And to be clear, it's not enough for `wait_for_workers` to just launch off a job, it also needs to poll on the client side.

**Comment by cailinw** [comment]
- [x] Implement `wait_for_cluster`
- [ ] Modify `create_cluster` and `create_job` to call `wait_for_clusters`
- [x] Modify `create_cluster` to accept a `num_initial_workers`
- [ ] Implement `wait_for_workers`
- [x] Implement `wait_for_job`
- [x] Add `nowait=false` parameter for `create_cluster`
- [x] Add `nowait=false` parameter for `create_job`

**Comment by calebwin** [comment]
@cailinw Can you also add a `nowait=false` parameter for `create_cluster` and `create_job`. By default, it should be false and wait until the cluster or job is created.

**Comment by calebwin** [comment]
@cailinw Is this finished? If so can you update the checklist above and close this?

**Comment by calebwin** [comment]
We did it!!! Awesome work @cailinw :tada:
