### ISSUE TITLE
Make cluster creation and notification easier for new users

### ISSUE THREAD

**Issue by cailinw** [banyan-team/banyan-julia#55]
"And when a user creates a new account, a default cluster should be created without any key pair. The creation of the cluster should also result in an email being sent to the user indicating that the cluster is ready for use."
Splitting issue from #23 

- [ ] Create default cluster for new user
- [x] Send email to user when cluster creation completes

**Comment by calebwin** [comment]
Thank you, Cleah!!!

We could do the default cluster thing but it might make people feel like the software is clunky because it takes so long to set up the account whereas cluster creation is like a known thing that it takes time for it to start up.
